In [2]:
import numpy as np
import random
from time import sleep

def create_board():
    return np.zeros((3, 3), dtype=int)

def possibilities(board):
    return [(i, j) for i in range(3) for j in range(3) if board[i, j] == 0]

def random_place(board, player):
    selection = possibilities(board)
    if selection:
        current_loc = random.choice(selection)
        board[current_loc] = player
    return board

def check_win(board, player):
    return (
        any(np.all(board == player, axis=0)) or  # Check columns
        any(np.all(board == player, axis=1)) or  # Check rows
        np.all(np.diag(board) == player) or  # Check main diagonal
        np.all(np.diag(np.fliplr(board)) == player)  # Check secondary diagonal
    )

def evaluate(board):
    for player in [1, 2]:
        if check_win(board, player):
            return player
    return -1 if np.all(board != 0) else 0

def play_game():
    board, winner, counter = create_board(), 0, 1
    print(board)
    sleep(2)
    
    while winner == 0:
        for player in [1, 2]:
            board = random_place(board, player)
            print(f"Board after {counter} move:")
            print(board)
            sleep(2)
            counter += 1
            winner = evaluate(board)
            if winner != 0:
                break
    
    return winner

# Driver Code
print("Winner is:", play_game())

def aStarAlgo(start_node, stop_node):
    open_set = {start_node}
    closed_set = set()
    g = {start_node: 0}
    parents = {start_node: start_node}
    
    while open_set:
        n = min(open_set, key=lambda x: g[x] + heuristic(x))
        
        if n == stop_node:
            path = []
            while parents[n] != n:
                path.append(n)
                n = parents[n]
            path.append(start_node)
            path.reverse()
            print('Path found: {}'.format(path))
            return path
        
        open_set.remove(n)
        closed_set.add(n)
        
        for (m, weight) in get_neighbors(n):
            if m in closed_set:
                continue
            
            if m not in open_set or g[m] > g[n] + weight:
                g[m] = g[n] + weight
                parents[m] = n
                open_set.add(m)
    
    print('Path does not exist!')
    return None

def get_neighbors(v):
    return Graph_nodes.get(v, [])

def heuristic(n):
    H_dist = {
        'A': 11, 'B': 6, 'C': 5, 'D': 7, 'E': 3, 'F': 6, 'G': 5,
        'H': 3, 'I': 1, 'J': 0
    }
    return H_dist.get(n, float('inf'))

Graph_nodes = {
    'A': [('B', 6), ('F', 3)],
    'B': [('A', 6), ('C', 3), ('D', 2)],
    'C': [('B', 3), ('D', 1), ('E', 5)],
    'D': [('B', 2), ('C', 1), ('E', 8)],
    'E': [('C', 5), ('D', 8), ('I', 5), ('J', 5)],
    'F': [('A', 3), ('G', 1), ('H', 7)],
    'G': [('F', 1), ('I', 3)],
    'H': [('F', 7), ('I', 2)],
    'I': [('E', 5), ('G', 3), ('H', 2), ('J', 3)],
    'J': []
}

aStarAlgo('A', 'J')


[[0 0 0]
 [0 0 0]
 [0 0 0]]
Board after 1 move:
[[0 0 1]
 [0 0 0]
 [0 0 0]]
Board after 2 move:
[[0 0 1]
 [0 0 0]
 [0 2 0]]
Board after 3 move:
[[1 0 1]
 [0 0 0]
 [0 2 0]]
Board after 4 move:
[[1 2 1]
 [0 0 0]
 [0 2 0]]
Board after 5 move:
[[1 2 1]
 [0 0 0]
 [0 2 1]]
Board after 6 move:
[[1 2 1]
 [0 2 0]
 [0 2 1]]
Winner is: 2
Path found: ['A', 'F', 'G', 'I', 'J']


['A', 'F', 'G', 'I', 'J']